#!/usr/bin/env python3
"""Print apply_patch chunks for a reproducible, standalone kernel-only proof.

Traverse imports, retain each whole module body, and re-elaborate the bodies
in dependency order. Only imports are removed; no theorem is assumed, sliced,
or replaced. No filesystem writes or network access. Generation is not proof
verification: the resulting file must itself finish a fresh Lean check.
"""
import argparse
import difflib
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "lean-r5"
OUTPUT = ROOT / "lean4web/Erdos1011R5KernelLean4Web.lean"
MANIFEST = ROOT / "verification/r5-kernel/R5_KERNEL_WEB_BUNDLE_MANIFEST.json"
CHUNK_BYTES = 24000


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def without_comments(source):
    """Remove nested Lean comments, preserving strings and line positions."""
    out, i, depth, quoted = [], 0, 0, False
    while i < len(source):
        if depth:
            if source.startswith("/-", i):
                depth += 1
                out.extend("  ")
                i += 2
            elif source.startswith("-/", i):
                depth -= 1
                out.extend("  ")
                i += 2
            else:
                out.append("\n" if source[i] == "\n" else " ")
                i += 1
        elif quoted:
            out.append(source[i])
            if source[i] == "\\" and i + 1 < len(source):
                i += 1
                out.append(source[i])
            elif source[i] == '"':
                quoted = False
            i += 1
        elif source.startswith("/-", i):
            depth = 1
            out.extend("  ")
            i += 2
        elif source.startswith("--", i):
            end = source.find("\n", i)
            end = len(source) if end == -1 else end
            out.extend(" " * (end - i))
            i = end
        else:
            if source[i] == '"':
                quoted = True
            out.append(source[i])
            i += 1
    if depth or quoted:
        raise ValueError("unterminated comment or string")
    return "".join(out)


def split_imports(source):
    code = without_comments(source)
    imports, kept = [], []
    for original, line in zip(source.splitlines(keepends=True), code.splitlines(keepends=True)):
        match = re.fullmatch(r"import\s+([\w.]+)\s*", line)
        if match:
            imports.append(match[1])
        else:
            if re.match(r"\s*(?:public\s+|meta\s+)?import\b", line):
                raise ValueError("unsupported import syntax: " + line)
            kept.append(original)
    return imports, "".join(kept)


def dependency_order(project=PROJECT):
    active, seen, order, external = set(), set(), [], set()

    def visit(name):
        if name in active:
            raise ValueError("cyclic local import: " + name)
        if name in seen:
            return
        active.add(name)
        path = project / (name.replace(".", "/") + ".lean")
        source = path.read_text()
        imports, body = split_imports(source)
        code = without_comments(body)
        if re.search(r"\b(?:native_decide|sorry|admit|axiom|unsafe|include_str)\b", code):
            raise ValueError("forbidden trust escape in " + name)
        for imp in imports:
            if imp == "R5Kernel" or imp.startswith("R5Kernel."):
                visit(imp)
            elif imp.startswith(("Mathlib.", "Lean.")):
                external.add(imp)
            else:
                raise ValueError("unsupported external import: " + imp)
        order.append((name, source, body, imports))
        active.remove(name)
        seen.add(name)

    visit("R5Kernel.Final")
    return order, sorted(external)


def raw_string(source):
    hashes = "#"
    while '"' + hashes in source:
        hashes += "#"
    return "r" + hashes + '"' + source + '"' + hashes


HEADER = '''
/-!
# Erdős #1011: r = 5, n ≥ 80, standard-three-axiom standalone proof

Generated by tools/prepare_r5_kernel_web.py from the local modular proof.
Every included module is re-elaborated from its complete source body.
Only Mathlib/Lean imports are needed; there are no project olean imports,
external files, network requests, native_decide calls, or asserted lemmas.
The final audit rejects every axiom outside the three standard Lean axioms.
Generation alone is not verification. See the separate local check record.
-/

set_option Elab.async false
set_option linter.all false
set_option maxErrors 1
set_option stderrAsMessages false

open Lean Elab Command

elab "r5_kernel_web_source " label:str ppSpace source:str : command => do
  liftIO <| (← IO.getStderr).putStrLn s!"R5_WEB_BEGIN {label.getString}"
  liftIO <| (← IO.getStderr).flush
  let (newEnv, messages) ← liftIO <| Lean.Elab.process source.getString
    (← getEnv) (← getOptions) (fileName := label.getString)
  for message in messages.toList do
    if message.severity == .error then logMessage message
  if messages.hasErrors then
    throwErrorAt source "standalone module failed: {label.getString}"
  modifyEnv fun _ => newEnv
  liftIO <| (← IO.getStderr).putStrLn s!"R5_WEB_END {label.getString}"
  liftIO <| (← IO.getStderr).flush

'''

FOOTER = '''
namespace Erdos1011KernelLean4Web

theorem formal_target_r5_ge80 :
    ∀ n : ℕ, 80 ≤ n →
      Erdos1011.M 5 n = n ^ 2 / 4 - 3 * n + 14 ∧
      Erdos1011.f 5 n = (n ^ 2 / 4 - 3 * n + 14) + 1 ∧
      Erdos1011.ThresholdExtremalOffset 5 n :=
  Erdos1011Kernel.formal_target_r5_ge80

#check formal_target_r5_ge80
#print axioms formal_target_r5_ge80
#eval Lean.versionString
run_cmd R5Kernel.checkStandardAxioms ``formal_target_r5_ge80

run_cmd do
  let axioms ← Lean.collectAxioms ``formal_target_r5_ge80
  let expected := #[``propext, ``Classical.choice, ``Quot.sound]
  unless axioms.size == 3 && expected.all axioms.contains do
    throwError "standalone final axiom set mismatch"
  Lean.logInfo "R5_KERNEL_WEB_FINISHED standard=3, extra=0, sorryAx=0"

end Erdos1011KernelLean4Web
'''


def render(project=PROJECT):
    order, external = dependency_order(project)
    pieces = ["\n".join("import " + x for x in external) + "\n", HEADER]
    modules = []
    for name, source, body, imports in order:
        pieces.append("r5_kernel_web_source " + raw_string(name) + "\n" + raw_string(body) + "\n\n")
        modules.append(dict(module=name, source_sha256=sha256(source.encode()),
                            body_sha256=sha256(body.encode()), imports=imports))
    pieces.append(FOOTER)
    text = "".join(pieces)
    manifest = dict(format_version=1, status="GENERATED_NOT_VERIFIED",
                    source=str(OUTPUT.relative_to(ROOT)), bytes=len(text.encode()),
                    source_sha256=sha256(text.encode()), modules=modules,
                    external_imports=external,
                    lean_toolchain=(project / "lean-toolchain").read_text().strip(),
                    lake_manifest_sha256=sha256((project / "lake-manifest.json").read_bytes()),
                    transformations=["remove import lines", "wrap whole module bodies in sequential Lean.Elab.process calls", "append original target alias and strict axiom audit"])
    return text, manifest


def chunks(text):
    result, lines, count = [], [], 0
    for line in text.splitlines(keepends=True):
        size = len(line.encode())
        if lines and count + size > CHUNK_BYTES:
            result.append("".join(lines))
            lines, count = [], 0
        lines.append(line)
        count += size
    if lines:
        result.append("".join(lines))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--summary", action="store_true")
    group.add_argument("--chunk", type=int)
    group.add_argument("--manifest", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--update", action="store_true",
                       help="print a patch updating an untouched generated bundle and manifest")
    args = parser.parse_args()
    text, manifest = render()
    parts = chunks(text)
    if args.summary:
        print(json.dumps(dict(modules=len(manifest["modules"]), bytes=manifest["bytes"],
                              chunks=len(parts), source_sha256=manifest["source_sha256"])))
        return
    if args.check:
        if OUTPUT.read_text() != text or json.loads(MANIFEST.read_text()) != manifest:
            raise ValueError("generated artifacts differ from current sources")
        print("Bundle and manifest reproduce exactly (not a Lean verification).")
        return
    print("*** Begin Patch")
    if args.update:
        old = OUTPUT.read_text()
        old_manifest = json.loads(MANIFEST.read_text())
        if sha256(old.encode()) != old_manifest["source_sha256"]:
            raise ValueError("refusing to update a modified generated bundle")
        for path, new in ((OUTPUT, text), (MANIFEST, json.dumps(manifest, indent=2) + "\n")):
            current = path.read_text()
            if current == new:
                continue
            print(f"*** Update File: {path}")
            diff = list(difflib.unified_diff(current.splitlines(), new.splitlines(), n=3))
            for line in diff[2:]:
                print("@@" if line.startswith("@@") else line)
        print("*** End Patch")
        return
    if args.manifest:
        if MANIFEST.exists():
            raise ValueError("refusing to overwrite existing manifest")
        print(f"*** Add File: {MANIFEST}")
        print("\n".join("+" + line for line in (json.dumps(manifest, indent=2) + "\n").splitlines()))
    else:
        index = args.chunk
        if not 0 <= index < len(parts):
            raise ValueError("invalid chunk number")
        before = "".join(parts[:index])
        addition = parts[index]
        if index == 0:
            if OUTPUT.exists():
                raise ValueError("refusing to overwrite existing bundle")
            print(f"*** Add File: {OUTPUT}")
        else:
            actual = OUTPUT.read_text()
            # apply_patch may normalize a chunk's trailing blank lines.
            # Restore only those exact missing newlines in the next chunk.
            if not (before.startswith(actual) and actual.endswith("\n")
                    and actual.rstrip("\n") == before.rstrip("\n")):
                raise ValueError("existing bundle prefix changed")
            addition = before[len(actual):] + addition
            print(f"*** Update File: {OUTPUT}\n@@")
            print(" " + actual.splitlines()[-1])
        print("\n".join("+" + line for line in addition.splitlines()))
        if index:
            print("*** End of File")
    print("*** End Patch")


if __name__ == "__main__":
    main()
